### Dodaj nowego gracza
POST http://localhost:8989/api/v1/players
Content-Type: application/json

{
  "name": "Trent Alexander-Arnold",
  "position": "Defender",
  "nationality": "England",
  "stats": {
    "appearances": 200,
    "goals": 10,
    "assists": 50,
    "yellowCards": 5,
    "redCards": 1
  },
  "contract": {
    "start": "2020-01-01",
    "end": "2025-12-31",
    "salary": 150000,
    "bonuses": {
      "goal": 3000,
      "assist": 2000
    }
  }
}

### Pobierz wszystkich graczy
GET http://localhost:8989/api/v1/players

### Pobierz gracza o określonym ID
GET http://localhost:8989/api/v1/players/67289ce2f8593d87ae74ebda

### Zaktualizuj dane gracza
PUT http://localhost:8989/api/v1/players/{{playerId}}
Content-Type: application/json

{
  "name": "Trent Alexander-Arnold",
  "position": "Right-back",
  "nationality": "England",
  "stats": {
    "appearances": 210,
    "goals": 12,
    "assists": 55,
    "yellowCards": 5,
    "redCards": 1
  }
}

### Usuń gracza
DELETE http://localhost:8989/api/v1/players/{{playerId}}

### Dodaj nowy mecz
POST http://localhost:8989/api/v1/matches
Content-Type: application/json

{
  "date": "2024-11-01",
  "opponent": "Arsenal",
  "score": "2-0",
  "stadium": {
    "name": "Anfield",
    "capacity": 54000,
    "location": "Liverpool, UK"
  },
  "goals": [
    { "playerId": "{{playerId}}", "minute": 15 },
    { "playerId": "{{playerId}}", "minute": 65 }
  ],
  "lineup": {
    "starting": ["{{playerId}}"],
    "substitutes": []
  }
}

### Pobierz wszystkie mecze
GET http://localhost:8989/api/v1/matches

### Pobierz mecz o określonym ID
GET http://localhost:8989/api/v1/matches/{{matchId}}

### Zaktualizuj dane meczu
PUT http://localhost:8989/api/v1/matches/{{matchId}}
Content-Type: application/json

{
  "date": "2024-11-01",
  "opponent": "Arsenal",
  "score": "3-1",
  "stadium": {
    "name": "Anfield",
    "capacity": 54000,
    "location": "Liverpool, UK"
  },
  "goals": [
    { "playerId": "{{playerId}}", "minute": 15 },
    { "playerId": "{{playerId}}", "minute": 65 },
    { "playerId": "{{playerId}}", "minute": 90 }
  ],
  "lineup": {
    "starting": ["{{playerId}}"],
    "substitutes": []
  }
}

### Usuń mecz
DELETE http://localhost:8989/api/v1/matches/{{matchId}}

### Dodaj nowe trofeum
POST http://localhost:8989/api/v1/trophies
Content-Type: application/json

{
  "name": "FA Cup",
  "topScorer": "{{playerId}}",
  "finalsWon": 1,
  "seasons": [
    { "year": 2023, "matchesWon": 5 }
  ]
}

### Pobierz wszystkie trofea
GET http://localhost:8989/api/v1/trophies

### Pobierz trofeum o określonym ID
GET http://localhost:8989/api/v1/trophies/{{trophyId}}

### Zaktualizuj dane trofeum
PUT http://localhost:8989/api/v1/trophies/{{trophyId}}
Content-Type: application/json

{
  "name": "FA Cup",
  "topScorer": "{{playerId}}",
  "finalsWon": 2,
  "seasons": [
    { "year": 2023, "matchesWon": 6 }
  ]
}

### Usuń trofeum
DELETE http://localhost:8989/api/v1/trophies/{{trophyId}}
